name = "Anxiom"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "A responsive business theme"

homepage = "https://github.com/pbklink/anxiom"
demosite = "https://pbklink.github.io/anxiom/"

tags = ["business","responsive"]

[author]
  name = "Paul Klink"
  homepage = "https://paul.klink.id.au/"

[original]
  name = "Trevor Bergeron"
  homepage = "https://sec.gd/"
